# Generated by Django 5.1 on 2024-09-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_user_alter_categorie_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='task_task_user_id_870aaf_idx',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['categorie', 'end_date', 'start_date', 'priority'], name='task_task_categor_110ed8_idx'),
        ),
    ]
